modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "cobbled_counter"
version = "1.5-forge-1.2.0"
displayName = "Cobblemon Counter"
description = '''
Counts things in Cobblemon
'''

[[dependencies.cobbled_counter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobbled_counter]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobbled_counter]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.5.0,)"
ordering = "NONE"
side = "BOTH"
